name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the main branch
      - uses: actions/checkout@v2
      
      # sets up .NET SDK 6.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.x
          
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish WordCounter/WordCounter.csproj -c Release -o release --nologo
        
      # changes the base-tag in index.html from '/' to 'WordCounter' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to WordCounter
        run: sed -i 's/<base href="\/" \/>/<base href="\/WordCounter\/" \/>/g' WordCounter/Pages/_Layout.cshtml
        
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: WordCounter/wwwroot
